name: simple-django-application-deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            set -e

            cd /home/ubuntu/django-simple-pwa

            git pull origin main

            source venv/bin/activate

            pip install -r requirements.txt

            python3 manage.py migrate --noinput

            python3 manage.py collectstatic --noinput || true

            pkill -f "manage.py runserver" || true

            nohup python3 manage.py runserver 0.0.0.0:8000 > django.log 2>&1 &

            echo "Deployment successful"
